// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: manifest.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

//
//Information kindly provided by EternalStudentDesuKa

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated struct PbManifest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var files: [PbFileInfo] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct PbFileInfo: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Path to the file relative to the game directory
  var filename: String = String()

  var chunks: [PbChunkInfo] = []

  /// 0 for files, 64 for directories. No other values were ever observed
  var flags: Int32 = 0

  /// Size of the entire file
  var size: Int32 = 0

  /// MD5 checksum of the entire file
  var md5: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct PbChunkInfo: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var chunkID: String = String()

  /// MD5 checksum of the uncompressed chunk data
  var md5: String = String()

  /// Offset at which this chunk should be put into the resulting file
  var offset: UInt64 = 0

  /// Size of the compressed chunk
  var compressedSize: UInt32 = 0

  /// Size of the uncompressed chunk
  var uncompressedSize: UInt32 = 0

  /// Xxhash checksum of the compressed chunk data
  var xxhash: UInt64 = 0

  /// MD5 checksum of the compressed chunk data (found in Starward / sophon-tools protos)
  var compressedMd5: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

nonisolated extension PbManifest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "Manifest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}files\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.files) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.files.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.files, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: PbManifest, rhs: PbManifest) -> Bool {
    if lhs.files != rhs.files {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension PbFileInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "FileInfo"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}filename\0\u{1}chunks\0\u{1}flags\0\u{1}size\0\u{1}md5\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.filename) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.chunks) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self.flags) }()
      case 4: try { try decoder.decodeSingularInt32Field(value: &self.size) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.md5) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.filename.isEmpty {
      try visitor.visitSingularStringField(value: self.filename, fieldNumber: 1)
    }
    if !self.chunks.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.chunks, fieldNumber: 2)
    }
    if self.flags != 0 {
      try visitor.visitSingularInt32Field(value: self.flags, fieldNumber: 3)
    }
    if self.size != 0 {
      try visitor.visitSingularInt32Field(value: self.size, fieldNumber: 4)
    }
    if !self.md5.isEmpty {
      try visitor.visitSingularStringField(value: self.md5, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: PbFileInfo, rhs: PbFileInfo) -> Bool {
    if lhs.filename != rhs.filename {return false}
    if lhs.chunks != rhs.chunks {return false}
    if lhs.flags != rhs.flags {return false}
    if lhs.size != rhs.size {return false}
    if lhs.md5 != rhs.md5 {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension PbChunkInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "ChunkInfo"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}chunk_id\0\u{1}md5\0\u{1}offset\0\u{3}compressed_size\0\u{3}uncompressed_size\0\u{1}xxhash\0\u{3}compressed_md5\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.chunkID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.md5) }()
      case 3: try { try decoder.decodeSingularUInt64Field(value: &self.offset) }()
      case 4: try { try decoder.decodeSingularUInt32Field(value: &self.compressedSize) }()
      case 5: try { try decoder.decodeSingularUInt32Field(value: &self.uncompressedSize) }()
      case 6: try { try decoder.decodeSingularUInt64Field(value: &self.xxhash) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self.compressedMd5) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.chunkID.isEmpty {
      try visitor.visitSingularStringField(value: self.chunkID, fieldNumber: 1)
    }
    if !self.md5.isEmpty {
      try visitor.visitSingularStringField(value: self.md5, fieldNumber: 2)
    }
    if self.offset != 0 {
      try visitor.visitSingularUInt64Field(value: self.offset, fieldNumber: 3)
    }
    if self.compressedSize != 0 {
      try visitor.visitSingularUInt32Field(value: self.compressedSize, fieldNumber: 4)
    }
    if self.uncompressedSize != 0 {
      try visitor.visitSingularUInt32Field(value: self.uncompressedSize, fieldNumber: 5)
    }
    if self.xxhash != 0 {
      try visitor.visitSingularUInt64Field(value: self.xxhash, fieldNumber: 6)
    }
    if !self.compressedMd5.isEmpty {
      try visitor.visitSingularStringField(value: self.compressedMd5, fieldNumber: 7)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: PbChunkInfo, rhs: PbChunkInfo) -> Bool {
    if lhs.chunkID != rhs.chunkID {return false}
    if lhs.md5 != rhs.md5 {return false}
    if lhs.offset != rhs.offset {return false}
    if lhs.compressedSize != rhs.compressedSize {return false}
    if lhs.uncompressedSize != rhs.uncompressedSize {return false}
    if lhs.xxhash != rhs.xxhash {return false}
    if lhs.compressedMd5 != rhs.compressedMd5 {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
